# Generated by Django 5.1.1 on 2024-10-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_rename_preco_total_pedido_precototal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='precototal',
        ),
    ]
