# Generated by Django 5.1.1 on 2024-10-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='pages',
            new_name='quantidade',
        ),
    ]
