# Generated by Django 5.1.1 on 2024-10-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
