# Generated by Django 5.1.1 on 2024-10-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
