# Generated by Django 4.1.13 on 2024-10-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_delete_statuspagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='status',
        ),
    ]
